### ISSUE TITLE
icon doesn't match riskmap

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-cards#17]
The icon is the same for all deployments. It should match the icon for the deployment per https://github.com/urbanriskmap/riskmap

**Comment by tomasholderness** [comment]
+1 Note tab icon vs logo in screenshot below.

<img width="739" alt="screen shot 2018-06-01 at 4 05 08 pm" src="https://user-images.githubusercontent.com/944642/40861063-bf21b8b6-65b5-11e8-8540-a49cc9b7e215.png">
