### ISSUE TITLE
missing flood_depth

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-cards#23]
@prittandrani reports a blank report card:
![093e146d-b7bf-4bd5-997c-ee1a7f5b0ae2](https://user-images.githubusercontent.com/2288238/32650541-48923674-c652-11e7-92fb-667a3b5f695e.jpeg)

@prittandrani can you please let us know the full URL? The screenshot cuts it off. We need to know as it may be just an old report? Results are not guaranteed for old reports as we have changed the schema over time. Also, you reported  that it "loaded slowly". Can you please confirm if it did in the end load? This is important as the only way I've been able to reproduce this is by loading reports for which flood_depth is null, see https://petabencana.id/map/jakarta/74725 for example, where the report **never** loads, because the following error is thrown:
```
Uncaught TypeError: Cannot read property 'flood_depth' of null
    at e.get (app-bundle.js:1)
    at e.evaluate (vendor-bundle.js:4)
    at t.bind (vendor-bundle.js:13)
    at t.bind (vendor-bundle.js:13)
    at t.bind (vendor-bundle.js:10)
    at t.bind (vendor-bundle.js:11)
    at t.bind (vendor-bundle.js:10)
    at e.t._show (vendor-bundle.js:12)
    at e._update (vendor-bundle.js:12)
    at e.conditionChanged (vendor-bundle.js:12)
    at t.e [as selfSubscriber] (vendor-bundle.js:11)
    at t.call (vendor-bundle.js:11)
    at t.setValue (vendor-bundle.js:11)
    at e.t.set [as condition] (vendor-bundle.js:11)
    at Object.setValue (vendor-bundle.js:4)
    at t.updateTarget (vendor-bundle.js:5)
```
which is because if you check the json data for that report at https://data.petabencana.id/reports/74725 , there is no flood_depth field:
```json
{
   "statusCode":200,
   "result":{
      "type":"Topology",
      "objects":{
         "output":{
            "type":"GeometryCollection",
            "geometries":[
               {
                  "type":"Point",
                  "properties":{
                     "pkey":"74725",
                     "created_at":"2017-11-09T10:31:00.000Z",
                     "source":"qlue",
                     "status":"confirmed",
                     "url":null,
                 "image_url":"https://lh3.googleusercontent.com/i8kEPu0sYoIcUPFrgvANYxCNCQgYVp40I7sADqjB-UDvdEpfGVgOXvbOu2Z4rcwAjX5K4YvNUTsa6gXcZEgz6DAu7o4d=s480-c",
                     "disaster_type":"flood",
                     "report_data":null,
                     "tags":{
                        "instance_region_code":"jbd",
                        "local_area_id":"151"
                     },
                     "title":" ",
                     "text":"Tlong di tl dnk bnjir udh mulai naik ni kali pesanggrahan gg.H.briti B kembangan selatan dari dlu kga pernh di tinjau am pemda setempat"
                  },
                  "coordinates":[
                     106.757523,
                     -6.186854
                  ]
               }
            ]
         }
      },
      "arcs":[

      ],
      "bbox":[
         106.757523,
         -6.186854,
         106.757523,
         -6.186854
      ]
   }
}
```
which suggests something is wrong in the cards with either 
1. validation that required data is entered, or
2. the put request, or
3. maybe this is just a really old report against old schema?

The test report I made the other day loads fine
https://data.petabencana.id/reports/74724

**Comment by matthewberryman** [comment]
@prittandrani writes:
"On the flood report, sorry I didn't take notes on the report number, but it showed at yesterday afternoon (Thu 9 Nov around 5pm jkt time) if that helps... I saw 3 reports that time and when clicking each of them it showed the same white box first, need to re-open it before it fully displayed."

Because the thank you tweets had been disabled (ping @talltom ) I cannot directly get the report id off twitter but will try and chase down the card ids based on time and from those the report id.

**Comment by matthewberryman** [comment]
@talltom correction: for the time window reported by @prittandrani the only tweet I can see per this search https://twitter.com/search?f=tweets&vertical=default&q=from%3Apetabencana%20cards.petabencana.id&src=typd that was submitted was mine (as linked above) which does show up immediately for me. There was a card link sent much earlier in the day that can't be it, and the later reports were 
(1) where the thank you tweets were working, since they came after mine that got a thank you
and
(2) not submitted anyway. 

So, bit of a mystery as to what the report was. The only one it could be based on @prittandrani's time window is my own report that does load. Based on that, it seems that the most likely explanation is actually a network issue. I suspect the blank reports I can see are just older ones, the card won't let me put 50cm in (so, some validation), and I checked and it is definitely submitting a flood_depth, which based on additional info from @prittandrani is not the source of error (since report popup is loading).  Closing this ticket unless we get more info.

**Comment by prittandrani** [comment]
Hi @matthewberryman et al , I tracked down the reports full URL from my web history, and these are the list of the reports:
[https://www.petabencana.id/map/jakarta/74725](https://www.petabencana.id/map/jakarta/74725) -- this is the same report Matthew found
[https://www.petabencana.id/map/jakarta/74687](https://www.petabencana.id/map/jakarta/74687)
[https://www.petabencana.id/map/jakarta/74685](https://www.petabencana.id/map/jakarta/74685)
These last two I opened at Thu Nov 9th, 15:15 Jkt time.

As per now (Fri Nov 10th, 20:41 Jkt time), when I go to those three links (I am using different network from yesterday) white page was still shown first:
![image](https://user-images.githubusercontent.com/22338984/32660959-95dd2f06-c657-11e7-90ce-4d91f3b0baeb.png)
When I refresh the page, it doesn't change. However, when I click close from the report pop-up, and then reopen it by clicking the waterdrop icon, it shows 'partially' loaded image but no text:
![image](https://user-images.githubusercontent.com/22338984/32661097-1e44a5f4-c658-11e7-9e9c-ee36c946a18d.png)

Also, the test report (probably from Matthew) works just fine: 
[https://www.petabencana.id/map/jakarta/74707](https://www.petabencana.id/map/jakarta/74707)
![image](https://user-images.githubusercontent.com/22338984/32661327-1f4a925a-c659-11e7-9379-cd4bde34257f.png)

As additional info, I am using Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Windows 7 and Safari on iOS 9.3.1 if that helps..

Thank you!

**Comment by tomasholderness** [comment]
Hi @matthewberryman and @prittandrani thanks for the information.

FYI in the future assign @asbarve and @ojha-url front-end (website) issues as this will be the quickest way of alerting them to the problem so they can take a lead on fixing. Thanks.

**Comment by matthewberryman** [comment]
@talltom I did assign to @asbarve and @ojha-url 

I have re-opened this ticket, and done some further investigation (now I'm caffeinated and not so tired) based on @prittandrani's info, and these reports are all qlue reports, so it's not a problem with cards but a frontend change on riskmap that's broken display of qlue reports.  I will open a ticket there after our skype @talltom

**Comment by matthewberryman** [comment]
(that's why I couldn't find them on twitter :) )
