### ISSUE TITLE
Deployment flag DEP=rm doesn't work

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-cards#3]
Off of the dev branch, doing:

export DEP=rm 
npm start 

should start the development server with the code for riskmap.in, but it still uses petabencana's card deck. It's the same way on the aws instance: https://cards.riskmap.in/flood/test123

**Comment by abrahamq** [comment]
To be clear, it does work on the test card, but does not correctly switch the submit and error cards- they still show up as petabencana even after building with DEP=rm.

**Comment by ojha-url** [comment]
Stuff in this still needs to be fetched by using deployment variables, i think it's hardcoded in locales. It'll work better than making changes inside locale files.
