### ISSUE TITLE
Change RiskMap.in Logo (currently old Risk Red)

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-cards#33]
<img width="724" alt="screen shot 2018-07-25 at 11 23 43 am" src="https://user-images.githubusercontent.com/944642/43210491-44b0a976-8ffd-11e8-82b9-72a6e9f8572e.png">

**Comment by matthewberryman** [comment]
Looks like this is done as it's coming up with shiny new blue logo
