### ISSUE TITLE
Remove re-direct to map on last card

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-cards#5]
_note: - this issue ported over from: https://github.com/urbanriskmap/petabencana.id/issues/205_

Details:
- user experience flow with cards should always start and end with the bot.
- last card should say something like: 

> Thank you for your report. You will receive a notification when it is on the map.

in case of image update failure:

> Thank you for your report. Your report will be added to the map, but the photo could not be uploaded. Please try again with a different image.

**Comment by tomasholderness** [comment]
@prittandrani could you or one of team provide Indonesian translations for the above messages?
Thanks

**Comment by prittandrani** [comment]
BI Translation for last card:
'Terima kasih untuk laporan Anda. Anda akan menerima notifikasi saat laporan Anda ditampilkan di peta.'

BI Translation for image update failure:
'Terima kasih untuk laporan Anda. Laporan Anda akan ditampilkan di peta, namun gambar tidak berhasil diunggah. Mohon coba lagi dengan gambar berbeda.'
