### ISSUE TITLE
Thank you card image scaling issue

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-cards#7]
- the logo is large, it doesn't always re-scale in in-app browser
![2017-08-22 15 23 30](https://user-images.githubusercontent.com/944642/29593385-f8e2ff28-8777-11e7-8723-b00373d2dcd4.png)

**Comment by ojha-url** [comment]
Fixed via https://github.com/urbanriskmap/cognicity-cards/commit/57d7656c26565f8f9de688060aca2d1c9498629b
